version: "3.9"

services:
  todo_app:
    container_name: todo_app
    build: .
    image: samuelige/todo_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=todo_live_db
      - PG_USER=postgres
      - PG_PASSWORD=12345
      - PG_HOST=todo_db
    depends_on:
      - todo_db
  
  todo_db:
    container_name: todo_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_live_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - todo_db_data:/var/lib/postgresql/data

volumes:
 todo_db_data: {}



